web/logintest/healths/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('record/', include('record.urls')),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('accounts.urls')),
]

web/logintest/record/urls.py
from django.urls import path
from . import views

app_name = 'record'

urlpatterns = [
    path('', views.main, name='main'),
    path('regist/<int:pk>', views.regist, name='regist'),
    path('chart/',views.chart,name='chart'),
    path('live/<int:pk>',views.live,name='live'),
    path('totalrecord/',views.totalrecord, name='totalrecord'),
    path('create/',views.create,name='create'),
    path('deepcreate/',views.deepcreate,name='deepcreate'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('stream2/',views.stream2,name='stream2'),
    path('page404/',views.page404,name='page404'),
    path('finish/<int:pk>/',views.finish,name='finish'),
    path('jsonrecord/',views.jsonrecord,name='jsonrecord'),
    path('video/<int:pk>/',views.video,name='video'),
    path('videoclose/<int:pk>/',views.videoclose,name='videoclose'),
    path('exside/<int:pk>/',views.exside,name='exside'),
    path('exfront/<int:pk>/',views.exfront,name='exfront'),
]

web/logintest/templates/base.html
{% load static%}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="shortcut icon" href="{% static 'favicon.ico' %}">
    <!-- CSS onsly -->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
      crossorigin="anonymous"
    />

    <title>Ai CO</title>
    {% comment %} <meta http-equiv="refresh" content="3"> {% endcomment %}
    
  </head>
  {% comment %} {% include 'head.html' %} {% endcomment %}
  <body>
    <div id='speak' style='display:none'>{{client2}}</div>


    <div class="container">
    {% include 'header.html' %}

    {% comment %}
    {% if user.is_authenticated %}
    <p>로그인 된상태</p>
    {% else %}
    <p>로그아웃 된상태</p>
    {% endcomment %}
    <main>
    {% block contents %} 
    {% endblock contents %}
    {% block content %} 
    {% endblock content %}
    </main>
  </div>
  <!-- JavaScript Bundle with Popper -->
  <script
  src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
  crossorigin="anonymous"
  ></script>
  <style>
    html,
    body {
      height: 100%;
    }
    
    body {
      display: flex;
      flex-direction: column;
      
      text-align: center;
      
      margin: 0;
    }
    
    main {
      flex: 1;
      
    }
  </style>
  {% include 'footer.html' %}
  <script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
  <script src="https://code.jquery.com/jquery-3.4.1.js"></script>
  <script>
    var value = localStorage.getItem('MSG');
    const userId = {{user.id}}
    console.log(value)
    setInterval(function () {
      const speak = document.querySelector('#speak').innerText
      if (speak == '스쿼트' && value !== '스쿼트') {
        localStorage.setItem('MSG',speak)
        window.location.href = 'http://192.168.100.106:8000/record/'
      }
      else if (speak == 'go' && value !== 'go') {
        localStorage.setItem('MSG',speak)
        window.location.href = `http://192.168.100.106:8000/record/live/${userId}`
      }
      else if (speak == 'stop' && value !== 'stop' && value =='start') {
        localStorage.setItem('MSG',speak) 
        window.location.href = `http://192.168.100.106:8000/record/finish/${userId}`
      }
      else if (speak == 'start' && value !== 'start' && value =='go') {
        localStorage.setItem('MSG',speak) 
        window.location.href = `http://192.168.100.106:8000/record/exfront/${userId}`
      }
      console.log(value)
      $("#speak").load(location.href + " #speak");
    }, 1000);
  </script>
  {% block script %}
  {% endblock script %}
  </body>
</html>

web/logintest/templates/footer.html
<div style = "text-align:center;margin-top:2px;">
    <div style="font-size:.6rem;">
        <span>공지사항</span> |
        <span>문의사항</span> |
        <span>서비스소개</span>

    </div>
    <div style="margin-top:1rem;">
        <h6>개발자집 막내아들</h6>
    </div>

</div>

web/logintest/templates/header.html
{% load static %}

<div style = "text-align:center; margin-bottom:2px;">
    <div>
        <a href="{% url 'record:main'%}">
            <img src="{% static 'aico.png' %}"/>
        </a>
    </div>

    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'record:main'%}">
            <img src="{% static 'banner.png' %}" style="width:40px; height:40px;"/>
        </a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              {% if user.is_authenticated %}

              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'record:live' user.id%}">운동시작</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'record:create'%}">기록하기</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'record:chart'%}">전체기록</a>
              </li>
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'record:totalrecord'%}">차트</a>
              </li>
              {% comment %} <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'record:deepcreate'%}">자동기록</a>
              </li> {% endcomment %}
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'record:regist' user.pk%}">기기관리</a>
              </li>
              {% comment %} <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'record:sosocket' %}">소소켓테스트</a>
              </li> {% endcomment %}
              {% endif %} 
            </ul>
            <div style = "text-align:right; margin-bottom:2px;">
              {% if user.is_authenticated %}
              <a>안녕하세요 {{ user.username }} 님 </a>&nbsp;&nbsp;
              <button  onclick="location.href='{% url 'account_logout' %}'" type="button" class="btn btn-outline-secondary">로그아웃</button>
              {% comment %} <a href="{% url 'account_logout' %}">로그아웃</a>&nbsp;&nbsp;&nbsp;&nbsp; {% endcomment %}
              {% else %}
              <a>로그인을 해주세요</a>&nbsp;&nbsp;
              {% endif %} 
              </div>
            
          </div>
        </div>
      </nav>
      
      
</div>