web/logintest/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('update', views.update, name='update'),
]

web/logintest/healths/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('record/', include('record.urls')),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('accounts.urls')),
]

web/logintest/record/urls.py
from django.urls import path
from . import views

app_name = 'record'

urlpatterns = [
    path('', views.main, name='main'),
    path('regist/<int:pk>', views.regist, name='regist'),
    path('chart/',views.chart,name='chart'),
    path('live/<int:pk>',views.live,name='live'),
    path('totalrecord/',views.totalrecord, name='totalrecord'),
    path('create/',views.create,name='create'),
    path('deepcreate/',views.deepcreate,name='deepcreate'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('stream2/',views.stream2,name='stream2'),
    path('page404/',views.page404,name='page404'),
    path('finish/<int:pk>/',views.finish,name='finish'),
    path('jsonrecord/',views.jsonrecord,name='jsonrecord'),
    path('video/<int:pk>/',views.video,name='video'),
    path('videoclose/<int:pk>/',views.videoclose,name='videoclose'),
    path('exside/<int:pk>/',views.exside,name='exside'),
    path('exfront/<int:pk>/',views.exfront,name='exfront'),
]

web/logintest/record/models.py
from django.db import models
from django.conf import settings

# Create your models here.
class Record(models.Model):
    exercise = models.CharField(max_length=50)
    count = models.IntegerField()
    time = models.IntegerField()
    date = models.DateField(auto_now_add=False)
    good = models.IntegerField()
    bad = models.IntegerField()
    user = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)

web/logintest/record/forms.py
from django import forms
from .models import Record
from django.forms.widgets import NumberInput
class RecordForm(forms.ModelForm):
    EXERCISE = [
            ('스쿼트','스쿼트'),
            ('푸쉬업','푸쉬업'),
            ('런지','런지'),
    ]
    exercise = forms.ChoiceField(choices=EXERCISE, widget=forms.Select())
    date = forms.DateTimeField(widget=NumberInput(attrs={'type': 'date'}), label="날짜")
    class Meta:
        model = Record
        # fields = ['excercise','count','time','date','perfect','good','bad']
        exclude = ('user',)

        # widgets = {
        #     "exercise" : forms.CharField(widget=
        #         attrs = {
        #             "class" : "form-control mt-2"
        #         }    
        #     ),
        #     "count" : forms.IntegerField(attrs={"class":"form-control mt-2"}),
        #     "time" : forms.IntegerField(attrs={"class":"form-control mt-2"}),
        #     "good" : forms.IntegerField(attrs={"class":"form-control mt-2"}),
        #     "bad" : forms.IntegerField(attrs={"class":"form-control mt-2"}),
        #     "date" : forms.DateField(attrs={"class":"form-control mt-2"}),
        # }

web/logintest/record/views.py
from django.shortcuts import render, redirect , get_list_or_404, get_object_or_404
from django.views.decorators.http import require_http_methods
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from .models import Record
# from .models import Record
from .forms import RecordForm
from .newSocketServer import Communication


# client = clients[0]["ID"]
# print(client)

import datetime
from django.http import StreamingHttpResponse
from .video3 import VideoCamera
from .userdata import Userdata
# Create your views here.
# cam = VideoCamera()

# 장고 서버실행시 소켓서버 함께 실행
communication = Communication(10000)
communication.start()
clients = communication.get_clients() # [{"ID" : "aicoaicoasdas", "IP" : "192.xxx.xxx.xx"}]
cam = 0

# 메인페이지 로그인후 진입
@login_required
def main(request):
    clients = communication.get_clients()
    if clients and clients[0]['MSG']:
        context = {

            'client' : clients,
            'client2' : clients[0]['MSG'][-1],
        }
        return render(request, 'record/main.html', context)
    else:
        return render(request,'record/main.html')


# 기기관리
@login_required
def regist(request,pk):
    clients = communication.get_clients()
    try: # globals()['user_{}'.format(pk)].check:
        if clients and clients[0]['MSG']:
            context = {
                'check' : globals()['user_{}'.format(pk)].check,
                'client2' : clients[0]['MSG'][-1],
            }
        else:
            context = {
                'check' : globals()['user_{}'.format(pk)].check,
            }
    except:
        if clients and clients[0]['MSG']:
            context = {
                'check' : 0,
                'client2' : clients[0]['MSG'][-1],
            }
        else:
            context = {
                'check' : 0,
            }
    return render(request, 'record/regist.html', context)


# 영상 서버 종료
def videoclose(request, pk):
    cam.server_socket.close()
    globals()['user_{}'.format(pk)].check = 0
    return redirect('record:regist',pk=pk)


# webcam 재생함수
def video(request, pk):
    global cam
    try:
        cam = VideoCamera()
    except:
        return redirect('record:main')
    # if globals()['user_{}'.format(pk)]:
    #     globals()['user_{}'.format(pk)].check = 0
    # else:

    globals()['user_{}'.format(pk)] = Userdata()
    cam.goods = -1
    cam.bads = -1
    cam.goodp = -1
    cam.badp = -1
    cam.anss = -1
    cam.ansp = -1
    cam.data = -1
    cam.cnt0,cam.cnt1 =0,0
    cam.cnt2_0, cam.cnt2_1 = 0,0
    cam.list_s = []
    return redirect('record:regist',pk=pk)
def gen(camera):
    while True:
        frame = cam.get_frame()
        yield(b'--frame\r\n'
            b'Content-Type: image/jpeg\r\n\r\n' + frame + b'\r\n\r\n')
def stream2(request):
    try:
        return StreamingHttpResponse(gen(()), content_type="multipart/x-mixed-replace;boundary=frame")
    except:  # This is bad! replace it with proper handling
        pass


bad = 0
# 실시간 운동영상 페이지
@login_required
def live(request, pk):
    clients = communication.get_clients()
    if not cam:
        return render(request,'record/regist.html')
    global bad
    bad +=1
    # 소켓ID랑 등록한 시리얼넘버가 같으면 live페이지 보여주기
    if clients and request.user.last_name == clients[0]['ID']:
    # if 'user_{}'.format(pk) in globals():
    #     print(globals()['user_{}'.format(pk)].check)
    #     if globals()['user_{}'.format(pk)].check == 1:    
        if clients[0]['MSG']:
            context = {
                'bad':bad,
                'camgoods' : cam.goods,
                'camgoodp' : cam.goodp,
                'cambads' : cam.bads,
                'camlists' : cam.list_s,
                'cambadp' : cam.badp,
                'camanss' : cam.anss,
                'camansp' : cam.ansp,
                'data':cam.data,
                'client2' : clients[0]['MSG'][-1],
            }
        else:
            context = {
                'bad':bad,
                'camgoods' : cam.goods,
                'camgoodp' : cam.goodp,
                'cambads' : cam.bads,
                'cambadp' : cam.badp,
                'camanss' : cam.anss,
                'camansp' : cam.ansp,
                'data':cam.data,
            }
        return render(request, 'record/live.html', context)
    return render(request, 'record/live.html')
    

#기록 삭제
@login_required
def delete(request, pk):
    try:
        record = get_object_or_404(Record,pk=pk)
        if record.user==request.user:
            if record:    
                record.delete()
                return redirect('record:chart')
        else:
            return redirect('record:404')
    except:
        return redirect('record:chart')


#에러 페이지
def page404(request):
    return render(request, 'record/page404.html')


# 날짜별 테이블 기록
@login_required
def chart(request):
    
    clients = communication.get_clients()
    records = list(Record.objects.all().values().order_by('-date'))
    records2 = []
    for i in records:
        if i['user_id'] == request.user.pk:
            if i['good']==0 and i['bad']==0: # b = 수행도
                b=0 
            else:
                b = 100*i['good'] / (i['good']+i['bad'])
                b = round(b,2)
            i['performance'] = b
            records2.append(i)
    if clients and clients[0]['MSG']:
        context = {
            'records2' : records2,
            'client2' : clients[0]['MSG'][-1],
        }
    else:
        context = {
            'records2' : records2,
        }
    return render(request, 'record/chart.html',context)


# 차트 기록 확인
@login_required
def totalrecord(request):
    clients = communication.get_clients()
    if clients and clients[0]['MSG']:
        context = {

            'client' : clients,
            'client2' : clients[0]['MSG'][-1],
        }
        return render(request, 'record/totalrecord.html', context)
    else:
        return render(request,'record/totalrecord.html')
# json 확인용
def jsonrecord(request):
    records = list(Record.objects.all().values().order_by('date'))
    squat = {} # 스쿼트 기록만
    pushup = {} # 푸쉬업 기록만
    lunge = {} # 런지 기록만
    myrecord = {'스쿼트':squat,'푸쉬업':pushup,'런지':lunge} # 내 기록만
    for i in records:
        if i['user_id'] == request.user.pk:
            if i['exercise'] == '스쿼트':
                cnt = squat.get(str(i['date'])) 
                if cnt:
                    squat[str(i['date'])] = cnt + i['count']
                else:
                    squat[str(i['date'])] = i['count']

            if i['exercise'] == '푸쉬업':
                cnt = pushup.get(str(i['date'])) 
                if cnt:
                    pushup[str(i['date'])] = cnt + i['count']
                else:
                    pushup[str(i['date'])] = i['count']

            if i['exercise'] == '런지':
                cnt = lunge.get(str(i['date'])) 
                if cnt:
                    lunge[str(i['date'])] = cnt + i['count']
                else:
                    lunge[str(i['date'])] = i['count']

    context = {
        'myrecord' : myrecord,
    }
    return JsonResponse(context)



# 기록 수동저장
@login_required
@require_http_methods(['GET', 'POST'])
def create(request):
    clients = communication.get_clients()
    if request.method == 'POST':
        form = RecordForm(request.POST)
        if form.is_valid():
            record = form.save(commit=False)
            record.user = request.user
            record.save()
            return redirect('record:chart')
    else:
        form = RecordForm()
    if clients and clients[0]['MSG']:
        context = {
            'form': form,
            'client' : clients,
            'client2' : clients[0]['MSG'][-1],
        }
    else:
        context = {
            'form' : form,
        }
    return render(request, 'record/create.html', context)


#스쿼트(전면) 시작
def exfront(request,pk):
    global exercise_kind, bad, cam
    exercise_kind = '스쿼트'
    bad, cam.goods, cam.bads, cam.anss = 0, 0, 0, 0
    return redirect('record:live',pk=pk)

#푸쉬업(측면) 시작
def exside(request,pk):
    global exercise_kind, bad
    exercise_kind = '푸쉬업'
    bad, cam.goodp, cam.badp, cam.ansp = 0, 0, 0, 0
    return redirect('record:live',pk=pk)



#운동종료
def finish(request,pk):
    global cam, bad
    if exercise_kind == '푸쉬업':
        a = { 
            'exercise' : exercise_kind,
            'count' : cam.goodp + cam.badp,
            'time' : bad,
            'good' : cam.goodp,
            'bad' : cam.badp,
        }
    elif exercise_kind == '스쿼트':
        a = { 
            'exercise' : exercise_kind,
            'count' : cam.goods + cam.bads,
            'time' : bad,
            'good' : cam.goods,
            'bad' : cam.bads,
        }
    Record(
        exercise = a['exercise'],
        count = a['count'],
        time = a['time'],
        date = datetime.datetime.now().date(),
        good = a['good'],
        bad = a['bad'],
        user = request.user,
    ).save()
    bad, cam.goodp, cam.badp, cam.ansp = 0, 0, 0, 0
    cam.goods, cam.bads, cam.anss = 0, 0, 0
    return redirect('record:live',pk=pk)



# 데이터 자동생성
@login_required
def deepcreate(request):
    a = { 
        'exercise' : '스쿼트',
        'count' : 1,
        'time' : 0,
        'good' : 3,
        'bad' : 3,
    }
    Record(
        exercise = a['exercise'],
        time = a['time'],
        # date = datetime.datetime.now().date(),
        date =  datetime.datetime.now().date(),
        good = a['good'],
        bad = a['bad'],
        count = a['good'] + a['bad'],
        user = request.user,
    ).save()
    return redirect('record:chart')


# STT데이터 통신
# 하드웨어로 이전

# @login_required
# def test(request):
#     from google.cloud import storage

#     bucket_name = 'tts_file'    # 서비스 계정 생성한 bucket 이름 입력
#     source_blob_name = 'file.wav'    # GCP에 저장되어 있는 파일 명
#     destination_file_name = './file.wav' # 다운받을 파일을 저장할 경로("local/path/to/file")

#     storage_client = storage.Client()
#     bucket = storage_client.bucket(bucket_name)

web/logintest/record/templates/record/chart.html
{% extends 'base.html' %}


{% block contents %}

</head>
<body>
	
  <br>
  <h1>운동기록</h1><br>
  <table id="products" border="1">
	<caption>
		<h5>페이지당 기록수 :</h5>
		<form action="" id="setRows">
			
			<p>
				<input type="text" name="rowPerPage" value="15">
			</p>
		</form>
	</caption>

	<thead>
		<tr>
			<th>운동</th>
			<th>날짜</th>
			<th>운동시간</th>
			<th>Good</th>
      <th>Bad</th>
      <th>수행도</th>
		</tr>
	</thead>
	<tbody>
    {% for record in records2 %} 
    <tr>
      <td>{{ record.exercise }}</td>
      <td>{{ record.date }} </td>
			<td>{{ record.time }} </td>
      <td>{{record.good}}</td>
      <td>{{record.bad}}</td>
      <td>{{record.performance}}% </td>
      <td>
				<a href="{% url 'record:delete' record.id %}">
				<i class="bi bi-dash-square"></i>
				X</a>
			</td>
    </tr>
    </tbody>
     {% endfor %}

	</tbody>
	</table>
</body>
</html>

<style>
  form {
    width: 500px;
  }
  table {
    border-collapse:collapse;
    margin:auto;
    margin-bottom: 10px;
  }
  th, td {
    padding: 3px 10px;
  }
  .off-screen {
    display: none;
  }
  #nav {
    width: 500px;
    text-align: center;
    margin : auto;
  }
  #nav a {
    display: inline-block;
    padding: 3px 5px;
    margin-right: 10px;
    font-family:Tahoma;
    background: #ccc;
    color: #000;
    text-decoration: none;
  }
  #nav a.active {
    background: #333;
    color: #fff;
  }
</style>
{% endblock contents %}


{% block script %}
<script>
var $setRows = $('#setRows');

$setRows.submit(function (e) {
	e.preventDefault();
	var rowPerPage = $('[name="rowPerPage"]').val() * 1;// 1 을  곱하여 문자열을 숫자형로 변환

//		console.log(typeof rowPerPage);

	var zeroWarning = 'Sorry, but we cat\'t display "0" rows page. + \nPlease try again.'
	if (!rowPerPage) {
		alert(zeroWarning);
		return;
	}
	$('#nav').remove();
	var $products = $('#products');

	$products.after('<div id="nav">');


	var $tr = $($products).find('tbody tr');
	var rowTotals = $tr.length;
//	console.log(rowTotals);

	var pageTotal = Math.ceil(rowTotals/ rowPerPage);
	var i = 0;

	for (; i < pageTotal; i++) {
		$('<a href="#"></a>')
				.attr('rel', i)
				.html(i + 1)
				.appendTo('#nav');
	}

	$tr.addClass('off-screen')
			.slice(0, rowPerPage)
			.removeClass('off-screen');

	var $pagingLink = $('#nav a');
	$pagingLink.on('click', function (evt) {
		evt.preventDefault();
		var $this = $(this);
		if ($this.hasClass('active')) {
			return;
		}
		$pagingLink.removeClass('active');
		$this.addClass('active');

		// 0 => 0(0*4), 4(0*4+4)
		// 1 => 4(1*4), 8(1*4+4)
		// 2 => 8(2*4), 12(2*4+4)
		// 시작 행 = 페이지 번호 * 페이지당 행수
		// 끝 행 = 시작 행 + 페이지당 행수

		var currPage = $this.attr('rel');
		var startItem = currPage * rowPerPage;
		var endItem = startItem + rowPerPage;

		$tr.css('opacity', '0.0')
				.addClass('off-screen')
				.slice(startItem, endItem)
				.removeClass('off-screen')
				.animate({opacity: 1}, 300);

	});

	$pagingLink.filter(':first').addClass('active');

});

$setRows.submit();
</script>
{% endblock script %}

web/logintest/record/templates/record/create.html
{% extends 'base.html' %}



{% block contents %}

  <h1 class="text-center">운동 기록</h1>
  {% comment %} <form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit">
  </form>
  <hr>
  <a href="{% url 'record:main' %}">[main]</a> {% endcomment %}
  
<div class="container" style="width: 25%;">

  <form method="post" class="post-form my-3">
      {% csrf_token %}
     
      {% if form.errors %}
          <div class="alert alert-danger" role="alert">
          {% for field in form %}
              {% if field.errors %}
              <strong>{{ field.label }}</strong>
              {{ field.errors }}
              {% endif %}
          {% endfor %}
          </div>
      {% endif %}


      <div class="form-group">
        <label for="exercise">운동</label>
        {% comment %} <input type="text" class="form-control" name="exercise" id="exercise"
        value="{{ form.exercise.value|default_if_none:'' }}"> {% endcomment %}
        <select class="form-control" name="exercise" id="exercise"
        value="{{ form.exercise.value|default_if_none:'' }}">
  
          <option>스쿼트</option>
          <option>푸쉬업</option>
          <option>런지</option>
          {% comment %} <option>4</option>
          <option>5</option> {% endcomment %}
        </select>
          {% comment %} <label for="exercise">운동</label>
          <input type="text" class="form-control" name="exercise" id="exercise"
                 value="{{ form.exercise.value|default_if_none:'' }}"> {% endcomment %}
      </div>
      <div class="form-group">
          <label for="count">횟수</label>
          <textarea class="form-control" name="count"
                    id="count" rows="1">{{ form.count.value|default_if_none:'' }}</textarea>
      </div>
 <div class="form-group">
        <label for="time">시간</label>
        <textarea class="form-control" name="time"
                  id="time" rows="1">{{ form.time.value|default_if_none:'' }}</textarea>
      </div>
      <div class="form-group">
        <label for="date">날짜</label>
        <input type="date" class="form-control" name="date"
        id="date">
        {% comment %} <textarea class="form-control" name="date"
                  id="date" rows="1">{{ form.date.value|default_if_none:'' }}</textarea> {% endcomment %}
    </div>
      <div class="form-group">
        <label for="good">good</label>
        <textarea class="form-control" name="good"
                  id="good" rows="1">{{ form.good.value|default_if_none:'' }}</textarea>
      </div>
  <div class="form-group">
    <label for="bad">bad</label>
    <textarea class="form-control" name="bad"
              id="bad" rows="1">{{ form.bad.value|default_if_none:'' }}</textarea>
</div>
<input type="submit" class="btn btn-outline-secondary">
</form>
</div>

{% endblock %}

web/logintest/record/templates/record/live.html
{% extends 'base.html' %} 
{%load static%}

{% block contents %}

<h4>Camera Live</h3>
<button class="btn btn-outline-secondary" onclick="imgToggle()">영상</button>
<br>
<!-- Your Connection -->


<img
id="img1"
style="-webkit-user-select: none"
src="{% url 'record:stream2' %}"
/>
<br>
<br>
<div id="goodbad">
  {% comment %} <h4>time : {{bad}}</h4> {% endcomment %}
  <h2>SQUAT</h2>
  <h4>Good : {{camgoods}}</h4>
  <h4>Bad : {{cambads}}</h4>
  {% comment %} <h5>list : {{camlists}}</h5> {% endcomment %}
<br>
  {% comment %} <h4>time : {{bad}}</h4> {% endcomment %}
  {% comment %} <h2>PUSHUP</h2>
  <h4>Good : {{camgoodp}}</h4>
  <h4>Bad : {{cambadp}}</h4> {% endcomment %}
</div>

<div id="times">

</div>
<a class="btn btn-outline-secondary" href="{% url 'record:exfront' user.id %}">스쿼트 시작</a>
<a class="btn btn-outline-secondary" href="{% url 'record:exside' user.id %}">푸쉬업 시작</a>
<a class="btn btn-outline-secondary" href="{% url 'record:finish' user.id %}">운동종료</a>
<br><br>
{% endblock contents %} 


{% block script %}
<script>
  setInterval(function () {
    $("#goodbad").load(location.href + " #goodbad");
  }, 500);

  {% comment %} setInterval(function () {
    $("#times").load(location.href + " #times");
  }, 1000);
   {% endcomment %}
  {% comment %} setInterval(function () {
    $("#position").load(location.href + " #position");
  }, 500); {% endcomment %}

  var cnt = 1;
  function imgToggle() {
    var img1 = document.getElementById("img1");
    if (cnt % 2 == 1) {
      img1.src = "{% url 'record:stream2' %}";
    } else {
      img1.src = "{% static 'mainimage.png' %}";
    }
    cnt++; // cnt 변수 1씩 증가 시키기
  }

</script>
{% endblock script %}

web/logintest/record/templates/record/main.html
{% extends 'base.html' %} {% load static %} {% block contents %}
<main>
  <br><br><br>
  <img src="{% static 'mainimage.png' %}" />
</main>

<style>
  main {
    height: 70vh;
  }
</style>

<script>

</script>
{% endblock contents %}

web/logintest/record/templates/record/regist.html
{% extends 'base.html' %} {% load static %} {% block contents %}
<main>
  <br><br>
  <a href="{% url 'accounts:update' %}"
    ><button class="btn btn-outline-secondary" id="serial">시리얼넘버 등록하기</button></a
  >
    {% if check %}
      <a href="{%url 'record:videoclose' user.id%}"><button class="btn btn-outline-secondary">서버연결해제</button></a>
    {% else %} 
       <a href="{%url 'record:video' user.id%}"><button type="button" id="modal_btn" class="btn btn-outline-secondary">기기연결하기</button></a>
    {% endif %}
    {% comment %} <p>pk : {{user.id}}</p>
    <p>check : {{ check}} </p> {% endcomment %}
  <img src="{% static 'mainimage.png' %}" />
</main>

<style>
  main {
    height: 70vh;
  }
</style>

<script>

</script>
{% endblock contents %}

web/logintest/record/templates/record/totalrecord.html
{% extends 'base.html' %} {% block contents %}

<!DOCTYPE HTML>
<html>
<head>
<script type="text/javascript" src="https://canvasjs.com/assets/script/jquery-1.11.1.min.js"></script>
<script type="text/javascript" src="https://canvasjs.com/assets/script/canvasjs.stock.min.js"></script>
<script type="text/javascript">
window.onload = function () {
  var dataPoints1 = [], dataPoints2 = [],  dataPoints3 = [];
  var stockChart = new CanvasJS.StockChart("chartContainer",{
    theme: "light2",
    animationEnabled: true,
    title:{
      text:"운동기록"
    },
//    subtitles: [{
//      text: "total record"
//    }],
    charts: [{
      axisY: {
        title: "운동 횟수"
      },
      toolTip: {
        shared: true
      },
      legend: {
            cursor: "pointer",
            itemclick: function (e) {
              if (typeof (e.dataSeries.visible) === "undefined" || e.dataSeries.visible)
                e.dataSeries.visible = false;
              else
                e.dataSeries.visible = true;
              e.chart.render();
            }
        },
      data: [{
        showInLegend: true,
        name: "스쿼트",
        yValueFormatString: "#,##0",
        xValueType: "dateTime",
        dataPoints : dataPoints1
      },{
        showInLegend: true,
        name: "푸쉬업",
        yValueFormatString: "#,##0",
        dataPoints : dataPoints2
      },{
        showInLegend: true,
        name: "런지",
        yValueFormatString: "#,##0",
        dataPoints : dataPoints3
      }]
    }],

  });
  $.getJSON("http://192.168.100.106:8000/record/jsonrecord/", function(data) {
    data1 = Object.keys(data.myrecord["스쿼트"])
    data2 = Object.keys(data.myrecord["푸쉬업"])
    data3 = Object.keys(data.myrecord["런지"])
    for(var i = 0; i < data1.length; i++){
      dataPoints1.push({x: new Date(data1[i]), y: Number(data.myrecord["스쿼트"][data1[i]])});
    }
    for(var i = 0; i < data2.length; i++){
      dataPoints2.push({x: new Date(data1[i]), y: Number(data.myrecord["푸쉬업"][data1[i]])});
    }
    for(var i = 0; i < data3.length; i++){
      dataPoints3.push({x: new Date(data1[i]), y: Number(data.myrecord["런지"][data1[i]])});
    }
    stockChart.render();
  });
}
</script>
</head>
<body>
  
<div id="chartContainer" style="height: 750px; width: 65%; margin:auto;"></div>

{% comment %} 넘어오는 json 파일 확인 {% endcomment %}
{% comment %} <a href="{%url 'record:jsonrecord'%}">json</a> {% endcomment %}
</body>
</html>

<br>
<hr>
{% endblock %}